services:
  web-development:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
      target: development
    ports:
      - "3001:3000"
    volumes:
      - "./src:/app/src:ro"
      - "./public:/app/public:ro"
  web:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: runner
    ports:
      - "3000:3000"

networks:
  default:
    name: clipfusion-network